### ISSUE TITLE
Design and implement configuration files

### ISSUE THREAD

**Issue by lventi** [My-DIGI-ID/aries-cloudagent-loadgenerator#12]
Configuration file should allow to define:

- versions of aca-py to be used in the test run
- horizontal scaling (no. of instances per each applicable component)
- test scenario
- load configuration (request rate, or other parameters according to the selected test scenario)
- duration of the test

**Comment by PaulWen** [comment]
Configurable via `./setup/.env` and `application.yaml` of Spring Boot
