### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by PaulWen** [My-DIGI-ID/aries-cloudagent-loadgenerator#4]

**Comment by lventi** [comment]
- [ ] - Project Description
- [ ] - Architecture Overview
- [ ] - Components Description
- [ ] - Installation and Usage
- [ ] - Configuration
- [ ] - Measured KPIs
- [ ] - Logs and Data Visualization
- [ ] - Troubleshooting
- [ ] - Related projects
- [ ] - References

**Comment by PaulWen** [comment]
Should create a new ticket if their is the need for more documentation
