### ISSUE TITLE
Scale the Postgres by setting up a Postgres Cluster

### ISSUE THREAD

**Issue by PaulWen** [My-DIGI-ID/aries-cloudagent-loadgenerator#48]
To further improve the performance of the Issuer/Verifier set up a Postgres cluster.

**Comment by iliecirciumaru** [comment]
PR to set a 3 instance Postgres Cluster: https://github.com/My-DIGI-ID/aries-cloudagent-loadgenerator/pull/49

**Comment by PaulWen** [comment]
@iliecirciumaru Is there anything left to do for this ticket?

**Comment by iliecirciumaru** [comment]
If we don't take into account arbitrary scalability, I think everything else is done
