### ISSUE TITLE
All docker-compose files should use the same network

### ISSUE THREAD

**Issue by PaulWen** [My-DIGI-ID/aries-cloudagent-loadgenerator#51]
Currently, communication between containers from the agent/loadgenerator networks to containers of the dashboard/logging network takes place via `localhost` of the host. To avoid this, all docker-compose files should use the same network and reference each other using the container names.

**Comment by iliecirciumaru** [comment]
@PaulWen Is it still relevant ?

**Comment by PaulWen** [comment]
While we are now using the same network for most of the containers, we are still using `host.docker.internal` instead of the container names in many places like `prometheus.yml`

**Comment by PaulWen** [comment]
https://github.com/My-DIGI-ID/aries-cloudagent-loadgenerator/commit/b184df4ce584138ea14a60ee78d073fca1844e52
